const Variant := {
    TYPE_BOOL: "bool",
    TYPE_INT: "int",
    TYPE_REAL: "float",
    TYPE_STRING: "string",
    TYPE_VECTOR2: "vector2",
    TYPE_RECT2: "rect2",
    TYPE_VECTOR3: "vector3",
    TYPE_TRANSFORM2D: "transform2d",
    TYPE_PLANE: "plane",
    TYPE_QUAT: "quat",
    TYPE_AABB: "aabb",
    TYPE_BASIS: "basis",
    TYPE_TRANSFORM: "transform",
    TYPE_COLOR: "color",
    TYPE_NODE_PATH: "node_path",
    TYPE_RID: "rid",
    TYPE_OBJECT: "object",
    TYPE_DICTIONARY: "dictionary",
    TYPE_ARRAY: "array",
    TYPE_RAW_ARRAY: "pool_byte_array",
    TYPE_INT_ARRAY: "pool_int_array",
    TYPE_REAL_ARRAY: "pool_real_array",
    TYPE_STRING_ARRAY: "pool_string_array",
    TYPE_VECTOR2_ARRAY: "pool_vector2_array",
    TYPE_VECTOR3_ARRAY: "pool_vector3_array",
    TYPE_COLOR_ARRAY: "pool_color_array",
}
